version: "3"

services:
  ####################################################################################################
  # Creating container PHP
  ####################################################################################################
  php:
    container_name: device_detect_backend
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - ./backend/:/var/www/html

####################################################################################################
# Creating container Nginx
####################################################################################################
  nginx:
    container_name: device_detect_nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  ####################################################################################################
  # Creating container frontend
  ####################################################################################################
  frontend:
    container_name: device_detect_frontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
     - '8081:8080'
    depends_on:
     - php
